version: "1"
services:
  apache:
    image: yanc0/alpine-python:latest
    ports:
      - 80:8080
    command: ['/usr/bin/dumb-init', '/usr/sbin/httpd', '-D', 'FOREGROUND']
    dev_overrides:
      volumes:
        - "$PWD/app:/var/www/localhost/htdocs"
      environment:
        - "DEBUG=1"
    options:
      kube:
        replicas: 3
  
registries:
  google:
    url: https://gcr.io
    namespace: meetup-ansible
